# Generated by Django 4.1.4 on 2022-12-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(max_length=500, verbose_name='Código del artículo')),
                ('nombre_articulo', models.CharField(max_length=500, verbose_name='Nombre del artículo')),
                ('descripcion_articulo', models.CharField(max_length=500, verbose_name='Descripción del artículo')),
                ('cantidad_disponible_del_articulo', models.IntegerField(verbose_name='Cantidad disponible del artículo')),
            ],
        ),
    ]
